name: "Create Release PR"
description: "Generate release branch & PR with LLM-powered notes and trigger deployment workflows"
inputs:
  openai_api_key:
    description: "OpenAI API key"
    required: true
  github_token:
    description: "GitHub token"
    required: true
  base_branch:
    description: "Base branch (default: main)"
    required: false
    default: "main"
  target_branch:
    description: "Target branch (default: production)"
    required: false
    default: "production"
  n8n_url:
    description: "n8n URL for deployment notifications"
    required: true
outputs:
  pr_url:
    description: "Created pull-request URL"
  deployed_workspaces:
    description: "List of workspaces that will be deployed"
runs:
  using: "composite"
