name: "Release Manager"
description: "Complete release management: generate notes, create PR, and trigger deployments"
inputs:
  openai_api_key:
    description: "OpenAI API key for generating release notes"
    required: true
  github_token:
    description: "GitHub token"
    required: true
  base_branch:
    description: "Base branch (default: main)"
    required: false
    default: "main"
  target_branch:
    description: "Target branch (default: production)"
    required: false
    default: "production"
  n8n_url:
    description: "n8n URL for deployment notifications"
    required: false
  mode:
    description: "Action mode: 'release' or 'deploy' or 'both' (default: both)"
    required: false
    default: "both"
outputs:
  pr_url:
    description: "Created pull-request URL"
  deployed_workspaces:
    description: "List of workspaces that will be deployed"
  triggered_workflows:
    description: "List of triggered workflow URLs"
runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Run TypeScript
      shell: bash
      run: bun run index.ts
      env:
        INPUT_OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_BASE_BRANCH: ${{ inputs.base_branch }}
        INPUT_TARGET_BRANCH: ${{ inputs.target_branch }}
        INPUT_N8N_URL: ${{ inputs.n8n_url }}
        INPUT_MODE: ${{ inputs.mode }}
