name: "Create Release PR"
description: "Generate release branch & PR with LLM-powered notes"
inputs:
  openai_api_key:
    description: "OpenAI API key"
    required: true
outputs:
  pr_url:
    description: "Created pull-request URL"
runs:
  using: "node20"
  main: "index.js"
