name: "Create Release PR"
description: "Generate release branch & PR with LLM-powered notes"
outputs:
  pr_url:
    description: "Created pull-request URL"
runs:
  env:
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  main: "index.js"
