name: Deploy Trigger

on:
  pull_request:
    types: [closed]
    branches: [production]

jobs:
  trigger_deployments:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Trigger Deployments
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base_branch: main
          target_branch: production
          n8n_url: ${{ secrets.N8N_URL }}
          mode: deploy
