# name: Test

# on:
#   push:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     permissions:
#       actions: write
#       contents: write
#       pull-requests: write
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install dependencies
#         run: npm install
#       - name: Create Release
#         uses: ./
#         with:
#           openai_api_key: ${{ secrets.OPENAI_API_KEY }}
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           base_branch: main
#           target_branch: production
#           n8n_url: ${{ secrets.N8N_URL }}
